#!/usr/bin/env bash
# automates ngnix

if [ "$(id -u)" -ne 0 ]
then
	exit 1
fi
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

sed -i '/}/i \
server {\
    listen 80;\
    listen [::]80 default_server;\
    root /var/www/html;\
    server_name _;\
\
    location /redirect_me {\
    return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
    }\
}\
' /etc/nginx/sites-available/default

service nginx restart
