#!/usr/bin/env bash
# automates ngnix

if [ "$(id -u)" -ne 0 ]
then
	exit 1
fi
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo -e "\nserver {\n    listen 80;\n    listen [::]:80 default_server;\n    root /var/www/html;\n    server_name _;\n\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n}" >> /etc/nginx/sites-available/default

service nginx restart
