#!/usr/bin/env bash
# Automating redirection
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 http://youtube.com;
	}
}" > /etc/nginx/sites-available/default
if service nginx status | grep -q "running"
then
	service nginx restart
else
	service nginx start
fi

