#!/usr/bin/env bash
# Automate 404
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chmod 644 /var/www/html/404.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me{
		return 301 http://youtube.com;
	}
	error_page 404 /404.html;
	location =/404.html {
		internal;
	}
}" > /etc/nginx/sites-available/default
if service nginx status | grep -q "running"
then
	service nginx restart
else
	service nginx start
fi
