#!/usr/bin/env bash
#installs Proxy and configures it

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

sudo echo "frontend http80
                bind *:80
		default_backend appservers
backend appservers
        balance roundrobin
	mode http
        server 530556-web-01 52.206.122.159:80 check
        server 530556-web-02 18.208.120.100:80 check
      " >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi 
