#!/usr/bin/env bash
#displays To infinity and beyond
#with sleep 2
#I am invincible when receiving a SIGTERM
while True
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
