#!/usr/bin/env bash
#displays numbers divisible by 3 and 5 as FizzBuzz
#displays numbers divisible by 3 as Fizz
#displays numbers divisible by 5 as Buzz
#other wise it displays the number
i=1
while [ "$i" -lt "101" ]
do
	if [ $(( i%15 )) -eq "0" ]
	then
		echo "FizzBuzz"
	elif [ $(( i%5 )) -eq "0" ]
	then
		echo "Buzz"
	elif [ $(( i%3 )) -eq "0" ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
