#!/usr/bin/env bash
#Loops and prints bad luck on 4, good luck on 8 and best school for the rest
i=0
while [ "$i" -lt "10" ]
do
	if [ "$i" = "3" ]
	then
		echo "bad luck"
	elif [ "$i" = "7" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
