#!/usr/bin/env bash
#Displays 4 and then bad luck from china
#Displays 9 and then bad luck from japan
#Displays 17 and then bad luck from Italy
i=1
while [ "$i" -lt "21" ]
do
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	i=$((i + 1))
done
