#!/usr/bin/env bash
#displays hours form 0 to 12
#displays minutes from 1 to 59
hour=0
minute=1
while [ "$hour" -lt "13" ]
do
	echo "Hour: $hour"
	while [ "$minute" -lt "60" ]
	do
		echo "$minute"
		minute=$((minute + 1))
	done
	minute=1
	hour=$((hour + 1))
done
