#!/usr/bin/env bash
#Displays the contents of the current directory
#Displays it in a list format
#part of the name after the first dash has been trimmed
for variable in *
do
	echo "${variable#*-}"
done
