#!/usr/bin/env bash
#Bash script that gives information about the school
if [ -f "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	echo "school is a regular file"
elif [ -d "school" ]
then
	echo "school exists but it's a directory"
else
	echo "school file does not exist"
fi
